[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["CS Club Open Source Team <dev@csclub.org.au>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
